config/routes.rb
Rails.application.routes.draw do

  root 'display#index'
  get '/cafe/:id' => 'display#show_place', as: 'show_place'

  get 'cart/create'

  devise_for :users

  ActiveAdmin.routes(self)

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized? (action, subject = nil)
    user.admin?
  end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :place

  validates :title, presence: true, length: { maximum: 70}
  validates :description, presence: true, length: { maximum: 200}
  validates :price, presence: true, numericality: true
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :dishes

  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>'},
                    default_url: 'images/:style/missing.png'

  validates_attachment_content_type :image,
                                    content_type: ['image/jpeg', 'image/gif', 'image/png']

  validates :title, presence: true, length: { maximum: 70}
  validates :description, presence: true, length: { maximum: 200}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :trackable, :validatable
  validates :name, presence: true, length: { maximum: 50}
  validates :phone, presence: true, length: { maximum: 50}
  validates :address, presence: true, length: { maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def accress_denied (exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController

    def index
      @places = Place.all
    end

    def show_place
      @place = Place.find(params[:id])
      @dishes_by_place = Dish.where(place_id: params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/views/display/index.html.erb
<h1>Food Shop</h1>


<ul>
  <div class="row">
    <% @places.each do |place| %>
        <div class="col-sm-4">
          <li class="cafe-info"><h2><%= link_to place.title, show_place_path(place) %></a></h2></li>
          <li class="cafe-info"><%= place.description %></li>
          <li class="cafe-info"><%= image_tag place.image.url(:medium) %></li>
        </div>
    <% end %>
  </div>

</ul>
</div>

app/views/display/show_place.html.erb
<h1><%= @place.title %></h1>

<ul>
  <div class="row">
    <div class="col-sm-8">
      <% @dishes_by_place.all.each do |dish| %>
          <li><a href="#"><%= dish.title %></a></li></br>
          <li><%= dish.description %></li></br>
          <li><%= dish.price %></li></br>
          <%= link_to 'Add to cart', cart_create_path %>
      <% end %>
    </div>

    <div class="col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">Cart</div>
            <div class="panel-body">
              <div class="row">
                  <div class="col-sm-9">
                    <%= %>
                  </div>
              </div>
        </div>
      </div>
    </div>
  </div>

</ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Food shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
      </ul>
      < class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Logged in as <%= current_user.name %>
            </p>
            <ul class="nav navbar-nav">
                  <% if current_user.admin? %>
                      <li><%= link_to 'Admin Panel', admin_root_path %></li>
                  <% end %>
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>